-- API_ITEM 테이블에 validation 컬럼 추가
ALTER TABLE api_item ADD COLUMN validation_enabled BOOLEAN;
ALTER TABLE api_item ADD COLUMN expected_values TEXT;

-- API_ITEM_HISTORY 테이블에 validation 컬럼 추가
ALTER TABLE api_item_history ADD COLUMN validation_enabled_snapshot BOOLEAN;
ALTER TABLE api_item_history ADD COLUMN expected_values_snapshot TEXT;

-- 확인을 위한 SELECT 문
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'API_ITEM' AND COLUMN_NAME IN ('VALIDATION_ENABLED', 'EXPECTED_VALUES');
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'API_ITEM_HISTORY' AND COLUMN_NAME IN ('VALIDATION_ENABLED_SNAPSHOT', 'EXPECTED_VALUES_SNAPSHOT');